name: build_avalonia

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build_forms.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/Prism.Core/**'
      - 'src/Prism.Events/**'
      - 'tests/Prism.Core.Tests/**'
      - 'src/Avalonia/**'
      - 'tests/Avalonia/**'

jobs:
  build-prism-avalonia:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@v1
    with:
      name: Build Prism.Avalonia
      solution-path: PrismLibrary_Avalonia.slnf
      dotnet-version: 9.0.302
      nugetFeedUrl: 'https://apinhousefeed.azurewebsites.net/v3/index.json'
    secrets:
      nugetUserName: ${{ secrets.IN_HOUSE_USER }}
      nugetToken: ${{ secrets.IN_HOUSE_API_KEY }}
